### ISSUE TITLE
其实现在云豆每天都要消耗10个

### ISSUE THREAD

**Issue by lycaste** [littlecodersh/MyPlatform#2]
RT。。。同时谢谢lz的分享，尤其那个微信扩展的，期待下文

**Comment by littlecodersh** [comment]
按照规则来说的确每个账号有应用就会出现10云豆每个月的消耗。
但实际上如果你新建一个小号用来挂SAE会出现不扣费的bug，我也不知道为什么。
![](http://7xrip4.com1.z0.glb.clouddn.com/MyPlatform%2F%E4%BA%91%E8%B1%86%E6%B6%88%E8%80%97.png)
所以，如果你本来就用SAE等于不收费，重开一个小号也是不收费:)
